-- Seed data for the cricket simulator database.
-- Idempotent: safe to re-run on an existing database.
-- Run after schema.sql has been applied.
--
-- Consolidated from the original schema.sql INSERT blocks and migrations 010-015.
-- ON CONFLICT clause preserves existing espn_id when incoming value is NULL,
-- and fills it in when the existing value is NULL.

INSERT INTO history.countries (espn_id, name, code) VALUES
    -- ── Core cricket nations (confirmed ESPN IDs + country codes) ──────────────
    (       1, 'England',                  'ENG'  ),
    (       2, 'Australia',                'AUS'  ),
    (       3, 'South Africa',             'SA'   ),
    (       4, 'West Indies',              'WI'   ),
    (       5, 'New Zealand',              'NZ'   ),
    (       6, 'India',                    'IND'  ),
    (       7, 'Pakistan',                 'PAK'  ),
    (       8, 'Sri Lanka',                'SL'   ),
    (       9, 'Zimbabwe',                 'ZIM'  ),
    (      11, 'United States',            'USA'  ),
    (      15, 'Netherlands',              'NED'  ),
    (      17, 'Canada',                   'CAN'  ),
    (      20, 'Papua New Guinea',         'PNG'  ),
    (      25, 'Bangladesh',               'BAN'  ),
    (      26, 'Kenya',                    'KENYA'),
    (      27, 'United Arab Emirates',     'UAE'  ),
    (      29, 'Ireland',                  'IRE'  ),
    (      30, 'Scotland',                 'SCOT' ),
    (      33, 'Nepal',                    'NEP'  ),
    (      37, 'Oman',                     'OMA'  ),
    (      40, 'Afghanistan',              'AFG'  ),
    -- ── Associate / geographic nations (ESPN IDs from migrations 010–015) ──────
    (      10, 'Fiji',                     NULL),
    (      12, 'Bermuda',                  NULL),
    (      13, 'Denmark',                  NULL),
    (      16, 'Malaysia',                 NULL),
    (      18, 'Gibraltar',                NULL),
    (      19, 'Hong Kong',                NULL),
    (      21, 'Argentina',                NULL),
    (      22, 'Israel',                   NULL),
    (      23, 'Singapore',                NULL),
    (      28, 'Namibia',                  NULL),
    (      31, 'Italy',                    NULL),
    (      32, 'Japan',                    NULL),
    (      34, 'France',                   NULL),
    (      35, 'Uganda',                   NULL),
    (      36, 'Germany',                  NULL),
    (      38, 'Kuwait',                   NULL),
    (      39, 'Cayman Islands',           NULL),
    (      41, 'Austria',                  NULL),
    (      42, 'Belgium',                  NULL),
    (      44, 'Chile',                    NULL),
    (      45, 'Malta',                    NULL),
    (      48, 'Zambia',                   NULL),
    (      57, 'Bahrain',                  NULL),
    (      60, 'Bahamas',                  NULL),
    (      61, 'Bhutan',                   NULL),
    (      63, 'Bulgaria',                 NULL),
    (      64, 'Belize',                   NULL),
    (      65, 'Botswana',                 NULL),
    (      66, 'Brazil',                   NULL),
    (      68, 'Cambodia',                 NULL),
    (      70, 'China',                    NULL),
    (      71, 'Cook Islands',             NULL),
    (      72, 'Croatia',                  NULL),
    (      74, 'Cyprus',                   NULL),
    (      75, 'Czechia',                  NULL),
    (      78, 'Estonia',                  NULL),
    (      80, 'Finland',                  NULL),
    (      82, 'Gambia',                   NULL),
    (      84, 'Ghana',                    NULL),
    (      86, 'Greece',                   NULL),
    (      88, 'Hungary',                  NULL),
    (      91, 'Indonesia',                NULL),
    (      96, 'Isle of Man',              NULL),
    (      97, 'Iran',                     NULL),
    (     103, 'Saudi Arabia',             NULL),
    (     108, 'Lesotho',                  NULL),
    (     110, 'Luxembourg',               NULL),
    (     113, 'Maldives',                 NULL),
    (     114, 'Mexico',                   NULL),
    (     115, 'Mongolia',                 NULL),
    (     118, 'Malawi',                   NULL),
    (     120, 'Mozambique',               NULL),
    (     122, 'Nigeria',                  NULL),
    (     124, 'Norway',                   NULL),
    (     128, 'Philippines',              NULL),
    (     132, 'Panama',                   NULL),
    (     134, 'Portugal',                 NULL),
    (     136, 'Qatar',                    NULL),
    (     137, 'Romania',                  NULL),
    (     140, 'Rwanda',                   NULL),
    (     141, 'Samoa',                    NULL),
    (     143, 'Seychelles',               NULL),
    (     144, 'South Korea',              NULL),
    (     145, 'Sierra Leone',             NULL),
    (     146, 'Slovenia',                 NULL),
    (     149, 'Spain',                    NULL),
    (     150, 'St Helena',                NULL),
    (     151, 'Suriname',                 NULL),
    (     152, 'Slovakia',                 NULL),
    (     153, 'Sweden',                   NULL),
    (     154, 'Switzerland',              NULL),
    (     156, 'Thailand',                 NULL),
    (     158, 'Turkey',                   NULL),
    (     160, 'Tanzania',                 NULL),
    (     165, 'Vanuatu',                  NULL),
    (    1043, 'Guernsey',                 NULL),
    (  218210, 'Costa Rica',               NULL),
    (  218211, 'Jersey',                   NULL),
    (  218212, 'Mali',                     NULL),
    (  300704, 'Cameroon',                 NULL),
    (  300708, 'Falkland Islands',         NULL),
    (  300710, 'Eswatini',                 NULL),
    (  891143, 'Serbia',                   NULL),
    ( 1116403, 'Myanmar',                  NULL),
    ( 1156232, 'Colombia',                 NULL),
    ( 1459373, 'Ivory Coast',              NULL),
    ( 1480823, 'Turks and Caicos Island',  NULL),
    ( 1508259, 'Timor-Leste',              NULL),
    -- ── Nations without ESPN IDs ───────────────────────────────────────────────
    (    NULL, 'United Kingdom',           NULL),
    (    NULL, 'Vietnam',                  NULL)
ON CONFLICT (name) DO UPDATE
    SET espn_id = COALESCE(EXCLUDED.espn_id, history.countries.espn_id);
